import { ArticleModel, TagModel } from '#/models/model';
import { createState } from 'solid-js';

interface HomeState {
  feedArticles: ArticleModel[];
  selectedFeed: 'global' | 'personal';
  tags: TagModel[];
}

const [homeState, setHomeState] = createState<HomeState>({
  feedArticles: [
    {
      title: 'test',
      slug: 'test-azailf',
      body: 'test',
      createdAt: '2019-12-06T20:46:04.207Z',
      updatedAt: '2019-12-06T20:46:04.207Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-j3wnh',
      body: 'test',
      createdAt: '2019-12-06T20:44:37.221Z',
      updatedAt: '2019-12-06T20:44:37.221Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-v9pb54',
      body: 'test',
      createdAt: '2019-12-06T20:43:11.232Z',
      updatedAt: '2019-12-06T20:43:11.232Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-nkb0fv',
      body: 'test',
      createdAt: '2019-12-06T20:41:50.232Z',
      updatedAt: '2019-12-06T20:41:50.232Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: 'test',
      slug: 'test-t6jn4',
      body: 'test',
      createdAt: '2019-12-06T20:39:17.239Z',
      updatedAt: '2019-12-06T20:39:17.239Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-m2atxc',
      body: 'test',
      createdAt: '2019-12-06T20:39:13.451Z',
      updatedAt: '2019-12-06T20:39:13.451Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-3c0yyc',
      body: 'test',
      createdAt: '2019-12-06T20:39:09.549Z',
      updatedAt: '2019-12-06T20:39:09.549Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-cu35oi',
      body: 'test',
      createdAt: '2019-12-06T20:39:03.110Z',
      updatedAt: '2019-12-06T20:39:03.110Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: 'test',
      slug: 'test-sjbukx',
      body: 'test',
      createdAt: '2019-12-06T20:37:03.819Z',
      updatedAt: '2019-12-06T20:37:03.819Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-pqqt4g',
      body: 'test',
      createdAt: '2019-12-06T20:36:55.917Z',
      updatedAt: '2019-12-06T20:36:55.917Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'satish2328',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
  ],
  selectedFeed: 'global',
  tags: [
    'test',
    'dragons',
    'training',
    'tags',
    'as',
    'coffee',
    'animation',
    'baby',
    'flowers',
    'cars',
    'money',
    'caramel',
    'japan',
    'happiness',
    'sugar',
    'clean',
    'cookies',
    'sushi',
    'well',
  ],
});
export { homeState, setHomeState };
